# Site settings
title: Hi, my name is Jonas Ångström.
description: 'I am a materials and data scientist looking for new job opportunities.'
url: 'https://d3hljalhk8t8so.cloudfront.net'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
disable_landing_page: false

author:
  name: 'Jonas Ångström'
  email: jonas.aangstroem@gmail.com
  twitter_username: AngstromJonas
  github_username:  jonasangstrom
  linkedin_username:  jonasangstrom
  scholar: https://scholar.google.com/citations?hl=en&user=pbYHl4UAAAAJ

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: public
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
